services:
    _defaults:
        autowire: true
        autoconfigure: true
    calculator:
        class: Misiyuk\MathBundle\Calculator\Calculator
    Misiyuk\MathBundle\Calculator\CalculatorInterface:
        alias: calculator
