services:
    _defaults:
        autowire: true
        autoconfigure: true
    calculator:
        class: Misiyuk\MathBundle\Calculator\Calculator
    Misiyuk\MathBundle\Calculator\CalculatorInterface:
        alias: calculator
    Misiyuk\MathBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,MathBundle.php}'
