services:
    _defaults:
        autowire: true
        autoconfigure: true
    calculator:
        class: Misiyuk\MathBundle\Math\Calculator\Calculator
    Misiyuk\MathBundle\Math\Calculator\CalculatorInterface:
        alias: calculator
    Misiyuk\MathBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,MathBundle.php}'
